### ISSUE TITLE
separator line in context menus on the  desktop are treated as menu entries

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#88]
No big deal, really, and very likely is an upstream problem. But I would like to report it anyway:
When I right click on the empty desktop or an icon and then use the arrow key down to select one menu entry after the other, the separator lines are working like menu entries and the selection stops there until I press the key again. Like that it takes two key-strokes to get from one entry to the next when there is a separator line in between ;)

**Comment by fasheng** [comment]
Thanks for the awesome bug report! I reported it to upstream and should be solved soon.

https://bugzilla.deepin.io/show_bug.cgi?id=1592

**Comment by oberon2007** [comment]
It's rare that someone is so happy about a bugreport :laugh: I like your style :)
Thank you.

**Comment by oberon2007** [comment]
This is still present with the latest pkgs. Greyed out items also count as entries.

**Comment by fasheng** [comment]
@hualet Help :)

**Comment by hualet** [comment]
@oberon2007 @fasheng I'll fix it :smile:

**Comment by hualet** [comment]
@fasheng I've fixed it, please review the code.

**Comment by oberon2007** [comment]
It's fine now, thank you! :)
