### ISSUE TITLE
transition to deepin-2015

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#99]
What is your opinion on the transition to deepin 2015 from the current state of packages? Will it be possible to update an installed system or will it be necessary to reinstall?

**Comment by fasheng** [comment]
We'd like to do some work to make updating to deepin-2015 smoothly. 

But there are two problems:
1.  some packages were re-factor by upstream, for example, dde-workspace was split to dde-dock and dde-launcher, gsettings schemas were put in new package named deepin-desktop-schemas, etc.
2.  some package's version format war changed and will break the upgrade rule, for example from `2014.3` to `3.0`

And considering @felixonmars will maintenance them in [community],  the heavy `epoch` keyword should be avoid. So the result may be pessimistic...

**Comment by felixonmars** [comment]
I have just added some of the deepin 2015 packages into [community], and more will come very soon.

https://www.archlinux.org/packages/community/x86_64/deepin-api/
https://www.archlinux.org/packages/community/x86_64/libdui/
https://www.archlinux.org/packages/community/x86_64/deepin-mutter/
https://www.archlinux.org/packages/community/any/deepin-desktop-schemas/
https://www.archlinux.org/packages/community/x86_64/deepin-wm/

BTW, the latest git HEAD version of dde-api doesn't build with gcc-go with an linker error: `/usr/lib/libXfixes.so.3: error adding symbols: DSO missing from command line`. Hope it's not something I missed :)

**Comment by oberon2007** [comment]
Talking about version numbers ;) Can someone explain to me what is going on with [dde-control-center](https://github.com/linuxdeepin/dde-control-center/releases) versioning?
2.3 > 2.90 > 2.4 > 2.3 ?

**Comment by fasheng** [comment]
Thanks felix.

I just plan to debug [arch-deepin:2015](https://build.opensuse.org/project/show/home:metakcahura:arch-deepin:2015) tonight, and you are always ahead of time. ;)

I'd like to see the latest DDE in arch official repository as soon as possible. But a fact is that, deepin-2015 is really unstable now, such as `dd-dock` and `dde-control-center` are broken in arhclinux. And some upstream packages(`deepin-default-gsettings`) will re-factor next week(sorry for the immature package architecture).

So in order to avoid unnecessary updating conflicts, how about let @mmetak and I solve such issues firstly? (it may takes one or two weeks)

Another thing, about package names, such as dde-api or deepin-api, libdui or libdeepin-ui. I just have a headache for this matter. Maybe we should have a discuss about it.

**Comment by fasheng** [comment]
@oberon2007 well, the correct order is 2.3->2.4->2.90->3.0. but the order of the tag's data may be not in linear. for example, we may take a tag `2.90.1` in branch `release/3.0` today, and take a tag `2.3.3` in branch `release/2.3` for a bugfix release tomorrow.

**Comment by oberon2007** [comment]
Ah, ok! I am somewhat released ... :laughing:

**Comment by oberon2007** [comment]
Is there a way to git clone the arch-deepin:2015 or should I familiarize myself with OBS to be able to achieve that?

**Comment by fasheng** [comment]
You mean to pull all the source code in OBS? Try the command
```
yaourt -S osc
osc checkout home:metakcahura:arch-deepin:2015
```
But a problem is that most of the PKGBUILD could not build sucess locally now, you must fix the source url manually which defined in _service file...

**Comment by felixonmars** [comment]
@fasheng I see, sorry for not contacting you beforehand :P

About the package names, since we are not splitting packages like Debian, I don't really want to add "lib" prefix etc only at downstream. For dde-api, I chose the name "deepin-api" because it's called that way inside the package anyway, and seems more consistent with other deepin packages. Personally I prefer "deepin-*" over "dde-*" simply because the latter was not used widely anyway, so I'd like to treat it like a codename :)

Also please let me know if I can help in any way for fixing the remaining packages!

**Comment by oberon2007** [comment]
Yes, great, @fasheng That works beautifully, thanks!

**Comment by fasheng** [comment]
@felixonmars Yes, sometimes the `dde-` prefix  will be misunderstood with `deepin-`.  It doesn't matter to uniform them to `deepin-`. And you could rename other packages to match the Archlinux style.

So since lots of pacakge names will be changed, I will not consider of the compability from arch-deepin:2015 to [community].

Here is my plan:
1.  make arch-deepin:2015 workable
2. ask for the developers to give tags to `dde-dock`/`dde-launcher`/`dde-session-ui`
3. re-factor some packages(`deepin-default-settings`, `deepin-default-gsettings`, `deepin-artwork`, `deepin-artwork-themes`)

If it goes well, three days is enough. And you don't need wait for me, just left the above packages. :-)

**Comment by mmetak** [comment]
@oberon2007 @felixonmars Just the other day I reported to @fasheng in IRC about the progress I've made in arch-deepin:2015. I managed to make some packages (dde-dock, dde-launcher, libdui, etc.) and I also reported some issues to @fasheng. Long story short, arch-deepin:2015 is very much so broken ATM. I barely played with it. ;-)
It's just a testing/playground from dde2015 in arch and is not meant to be used for production. EVER.
When it stabilizes and the issues are ironed out @felixonmars will move the packages to community anyway. What do you think @fasheng?

**Comment by oberon2007** [comment]
Perfectly fine for me. Thanks for the clarification, @mmetak From the manjaro perspective it will just be important that new packages of the same name as 2014-packages do not travel to arch community prematurely, because they would automatically update in manjaro and break those systems... Well the problem is not too big right now, since most packages are custom built and renamed to "-manjaro" anyway atm. In any case it's great for me to also play around with those future packages to get accustomed to the changes when they are ready...

**Comment by mmetak** [comment]
@felixonmars already imported deepin-api (dde-api) into community and I'm thinking what would be the best way to tackle this issue since there will be file conflicts when installing 'deepin' group.

**Comment by oberon2007** [comment]
How about removing deepin-api temporarily from group deepin? dde-api is still available from your repo! ...

**Comment by mmetak** [comment]
I think it would be best to just remove it from my repo and make some workarounds to pkgbuild files in obs to depend on deepin-api instead?

**Comment by oberon2007** [comment]
Looks like it concerns only **dde-control-center** and **dde-dock-applets**.

**Comment by oberon2007** [comment]
And then I guess **deepin-api** will need ``replace=dde-api``

**Comment by fasheng** [comment]
OK, after think again, the fixed plan is:

1. adjust upstream package architecture and fix broken issues in OBS/arch-linux:2015 to ensure it workable, especially dde-dock, dde-launcher and dde-control-center
2. then after @mmetak and I think it is stable enough, will notice @felixonmars to continue the work for [community]

About to rename packages, just let @felixonmars to do such work, and it's best to make it compatibility with old packages, such as adding `replace` keywords.

For the packages already in [community],  @felixonmars said will remove `deepin-api` from `deepin` group, so it is harmless for us only if you install it manually.  And for `libdui`, `deepin-mutter`, `deepin-desktop-schemas` and `deepin-wm`, they are all new packages in 2015, so just keep them in [community] and remove same package in `arch-deepin:2015`.

**Comment by fasheng** [comment]
dde-dock/dde-launcher/dde-session-ui/libdui/deepin-metacity/deepin-desktop-base(not porting required, but it owns the default background) synced to Github with tags now.

**Comment by fasheng** [comment]
`dde-dock`/`dde-launcher`/`dde-session-ui`/`dde-control-center`/`dde-wm` works now, but still are experimental...

**Comment by fasheng** [comment]
Here is the fixed issues today
-   dde-control-center
    -   [X] no theme list in \`Appearance\` module
-   dde-daemon
    -   [X] enter "Date and Time" module cause system blocked
    -   [X] panic when changing wallpapers
        1.  missing default wallpaper
        2.  fix the default theme font name, use `FontName=DejaVu
                        Sans` instead of `FontName=Source Han Sans SC`
    -   [X] panic when changing keybindings
-   deepin-file-manager-backend
    -   [X] it takes too long time(10s) to popup menu dialog when
        clicking right button

And most known issues in upstream and the time probably needed
-   dde-control-center (3weeks)
    -   [ ] network module rewriting now
    -   [ ] bluetooth module rewriting now
-   dde-dock (unknown)
    -   [ ] drawing tray icons with black dirty background
-   dde-session-ui (2weeks)
    -   [ ] lightdm-deeppin-greeter still to be improved
    -   [ ] dde-lock rewriting now
    -   [ ] dde-osc rewriting now
-   deepin-wm (unknown)
    -   [ ] wallpaper drawing failed in sometimes

and I have some special work to do in the following days this week, so the fixing process may be delayed during the time..

**Comment by felixonmars** [comment]
Nice work, thanks!

**Comment by SolarAquarion** [comment]
deepin-api is in the repo but the 2015/2014 repo is still asking for dde-api

**Comment by oberon2007** [comment]
@SolarAquarion , my understanding is that deepin-api, which is going to replace dde-api is in the repo already a little prematurely. For now dde-api is still the one being used as a dependency.

**Comment by oberon2007** [comment]
@fasheng , I am confused now about which PKGBUILDS to use to update for the existins manjaro-deepin installs. I thought I would just continue with the obs PKGBUILD from this (2014) github repo here and the version numbers of the pkgs currently in arch community suggest that those have been used for your Nov 3 Packages. But when I try to build dde-workspace now I get these build errors:
```
app/desktop/CMakeFiles/desktop.dir/build.make:310: recipe for target 'dde-desktop' failed
make[2]: *** [dde-desktop] Error 1
CMakeFiles/Makefile2:302: recipe for target 'app/desktop/CMakeFiles/desktop.dir/all' failed
make[1]: *** [app/desktop/CMakeFiles/desktop.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by oberon2007** [comment]
also a problem with startdde:
```app/shutdown/CMakeFiles/shutdown.dir/build.make:174: recipe for target 'dde-shutdown' failed
make[3]: *** [dde-shutdown] Error 1
make[3]: Leaving directory '/build/startdde-manjaro/src/startdde/dialogUI/build'
CMakeFiles/Makefile2:218: recipe for target 'app/shutdown/CMakeFiles/shutdown.dir/all' failed
make[2]: *** [app/shutdown/CMakeFiles/shutdown.dir/all] Error 2
make[2]: Leaving directory '/build/startdde-manjaro/src/startdde/dialogUI/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/build/startdde-manjaro/src/startdde/dialogUI/build'
Makefile:31: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by mmetak** [comment]
@oberon2007 is something wrong with the pkgbuild files in arch-deepin branch?

**Comment by oberon2007** [comment]
I am currently using these: https://github.com/fasheng/arch-deepin/tree/master/obs/home:metakcahura:arch-deepin (building in a clean chroot environment) Are they the ones to use right now? They give me the above errors.

**Comment by mmetak** [comment]
OBS just rebuilt all the packages just fine like two hours ago... btw, yes those are the right ones, but fasheng should do a quick obs-sync it seems some of them need to be updated.

**Comment by fasheng** [comment]
I see, the obs snapshot code in github/arch-deepin is out of date now, please checkout code from OBS directly instead. :)





2015年11月5日 下午12:56, 下午12:56，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
I was already suspecting they were not up-to-date because for example version of the actual pkg dde-control-center is 2.90.3-2 while the PKGBUILD is still at pkgrel 1

**Comment by oberon2007** [comment]
Yes, I will use OBS PKGBUILDs in the future :) Thank you both! :)

**Comment by mmetak** [comment]
@oberon2007 I suggest for you to simply checkout the repo with osc and keep updating it with 'osc up' from within the project directory. That way you'll always have the latest.
Also, when the deepin team finishes their work upstream with refactoring dde-workspace and fixing some other issues and later we get our arch-deepin:2015 branch somewhat usable for testing you're more then welcome to help testing and if you're interested maybe creating an account in obs if you would like to contribute? I'll add you to project maintainers with write access.

Also, another mention for @SolarAquarion and anyone else reading this:
Please, don't use the 2015 branch. If everything goes well it should only exist temporarily for initial packaging and testing later on before @felixonmars continues importing the packages to community repo.

**Comment by oberon2007** [comment]
Thank you very much, @fasheng ! :)
Well I have now cloned dde-workspace with osc and a get the same error :/ What else can be wrong on my end??

**Comment by oberon2007** [comment]
Ah. maybe I simply need to rebuild my libdeepin-webkit first ... I had put that in our repos, too in order to be able to build the other pkgs with the manjaro tools ...

**Comment by fasheng** [comment]
ehmm, I'm not sure the reason for there is no computer to use around. maybe you could have a try for github/arch-deepin/pkgbuilds/dde-daemon, it should build success.



2015年11月5日 下午8:03, 下午8:03，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Ok. Rebuilding **libdeepin-webkit** fixed it. Thank you! :)

**Comment by fasheng** [comment]
@felixonmars 
Here is the package list that could be moved(or updated) to [community] now.

| package               |      tag | commit   | note     |
|-----------------------|----------|----------|----------|
| dbus-generator        |    0.6.2 | gbf4bf4a |          |
| dde-account-faces     |    1.0.8 | gb7bde27 |          |
| deepin-artwork-themes |  15.10.1 | gaa39fbc |          |
| deepin-cursor-theme   |  15.10.0 | g8cf999d |          |
| deepin-grub2-themes   |    1.0.0 | g5d65132 |          |
| deepin-gtk-theme      |   3.18.0 | g67e0b31 |          |
| deepin-icon-theme     |  15.10.0 | geeb1a8d |          |
| deepin-mutter         | 3.18.1.1 | g8190230 |          |
| deepin-sound-theme    |  15.10.0 | g038f661 |          |
| plymouth-theme-deepin |  15.10.1 | gcbe7b63 | optional |

`The package name is the one in github/linuxdeepin`

All packages should own a Makefile, if can't work please let me known.

More tags for app packages(deepin-movie, deepin-music, etc) will comes later. :)

@mmetak
For DDE related packages, though many improve work still in process in upstream, but the basic stability is guaranteed now. So I think move them to [community] as an alpha version would be OK. I updated packages to latest version just now, please have a try. ;)

**Comment by felixonmars** [comment]
OK, thank you. So `deepin-wm` was superseded by `deepin-mutter`?

**Comment by fasheng** [comment]
Yes, and deepin-wm don't need rebuild this time.



2015年11月17日 下午10:33, 下午10:33，在 Felix Yan <notifications@github.com> 已写:

**Comment by felixonmars** [comment]
I see. I've bumped most of the packages now, and I'll leave plymouth-theme-deepin behind for now as we don't have any plymouth in our repos. I'll start to experiment with DDE-related packages tomorrow :)

**Comment by oberon2007** [comment]
This is maybe a stupid question but ... what exactly is deepin-mutter needed for now?
At the moment in any case I get:
```
$ deepin-mutter
(deepin-mutter:3655): GLib-GIO-ERROR **: Settings schema 'com.deepin.wrap.gnome.desktop.peripherals.mouse' is not installed
Trace/breakpoint trap (core dumped)
```
Suppose it will need the new **deepin-desktop-schemas** ?

**Comment by fasheng** [comment]
Thanks. About deepin-mutter, I remember the old version of in [community] still is 3.16 instead of 3.18 just now, so rebuild deepin-wm is required. Maybe you have did it :)



2015年11月17日 下午11:15, 下午11:15，在 Felix Yan <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
I don't even have deepin-wm installed!

**Comment by oberon2007** [comment]
I am confused now, sorry! Is deepin-wm a new (2015) pkg?

**Comment by felixonmars** [comment]
@fasheng No. There was no soname bump and I didn't encounter any issues, so I didn't rebuild it yet.

**Comment by oberon2007** [comment]
Obviously, since it depends on **deepin-desktop-schemas** ;)

**Comment by fasheng** [comment]
yes, deepin-wm is a new wm to replace of deepin-compiz in 2015. and as a general wm, you could use it without limitation.



2015年11月18日 上午12:37, 上午12:37，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by fasheng** [comment]
works fine is just ok :)



2015年11月18日 上午12:43, 上午12:43，在 Felix Yan <notifications@github.com> 已写:

**Comment by felixonmars** [comment]
One more question: is gtk-engine-unico really requested? It should be useless since GTK 3.16+...
https://blogs.gnome.org/mclasen/2014/10/23/an-early-view-of-gtk-3-16/

**Comment by oberon2007** [comment]
So **startdde** still depends on **deepin-compiz** whil **deepin-wm** replaces **deepin-compiz**, but these two are not conflicting?

**Comment by oberon2007** [comment]
And how to solve the conflicting files in **/usr/share/glib-2.0/schemas** when installing the new **deepin-desktop-schemas** ? Will ``replaces=deepin-default-gsetting`` in deepin-desktop-schemas solve that? Or is it more complicated than that?

**Comment by oberon2007** [comment]
```
pacman -Qo /usr/share/glib-2.0/schemas/
/usr/share/glib-2.0/schemas/ is owned by colord 1.2.12-1
/usr/share/glib-2.0/schemas/ is owned by dconf-editor 3.18.2-1
/usr/share/glib-2.0/schemas/ is owned by dde-daemon 2.92.0-2
/usr/share/glib-2.0/schemas/ is owned by deepin-compiz 1:0.9.99.5.20140707164843-8
/usr/share/glib-2.0/schemas/ is owned by deepin-manjaro-gsettings 20151116-2
/usr/share/glib-2.0/schemas/ is owned by deepin-manjaro-workspace 2.90.1-5
/usr/share/glib-2.0/schemas/ is owned by deepin-mutter 3.16.3.0-2
/usr/share/glib-2.0/schemas/ is owned by evince 3.18.2-1
/usr/share/glib-2.0/schemas/ is owned by gcr 3.18.0-1
/usr/share/glib-2.0/schemas/ is owned by geoclue 0.12.99-2
/usr/share/glib-2.0/schemas/ is owned by glib2 2.46.1-1
/usr/share/glib-2.0/schemas/ is owned by gnome-online-accounts 3.18.2.1-1
/usr/share/glib-2.0/schemas/ is owned by gnome-settings-daemon 3.18.2-1
/usr/share/glib-2.0/schemas/ is owned by gsettings-desktop-schemas 3.18.1-1
/usr/share/glib-2.0/schemas/ is owned by gstreamer0.10-bad-plugins 0.10.23-11
/usr/share/glib-2.0/schemas/ is owned by gthumb 3.4.1-1
/usr/share/glib-2.0/schemas/ is owned by gtk3 3.18.5-1
/usr/share/glib-2.0/schemas/ is owned by gvfs 1.26.2-1
/usr/share/glib-2.0/schemas/ is owned by gvfs-smb 1.26.2-1
/usr/share/glib-2.0/schemas/ is owned by libcryptui 3.12.2-1
/usr/share/glib-2.0/schemas/ is owned by libgweather 3.18.1-1
/usr/share/glib-2.0/schemas/ is owned by metacity-ubuntu 2.34.13.0ubuntu4.1-7
/usr/share/glib-2.0/schemas/ is owned by mousepad 0.4.0-1
/usr/share/glib-2.0/schemas/ is owned by nautilus 3.18.2-1
/usr/share/glib-2.0/schemas/ is owned by startdde-manjaro 2.91.0-4
```
Phew!

**Comment by oberon2007** [comment]
Well it looks like it's impossible to install **deepin-desktop-schemas** and **dde-daemon** at the same time...
Can you please explain to me again which packages are to be removed now? deepin-workspace? dde-daemon aswell??

**Comment by fasheng** [comment]
@felixonmars
For depends of `deepin-mutter`, please use `deepin-desktop-schemas` instead of `gsettings-desktop-schemas` and `gnome-settings-daemon`.

For `gtk3-engines-unico`, you are right, just remove it from depends.

**Comment by felixonmars** [comment]
OK, both updated.

**Comment by fasheng** [comment]
@oberon2007 
For the checksums problem which is a troublesome issue of OBS for Archlinux users that the the checksums will be out of date after package rebuild without version changed. Sometimes we will increase `pkgrel` manually to avoid such issues, but most of the cases, please install the packages manually through `pacman -U`.

For the conflicting issues from 2014 to 2015 especially for manjaro-deepin , I think @felixonmars will dispatch some of them after all packages moved to [community].

**Comment by oberon2007** [comment]
@fasheng and @felixonmars for me at the moment it would just be important to know which pkgs will drop away and which ones are going to be used. Sofar I have not found a way to install deepin-desktop-schemas due to conflicting packages... I am just afraid that one day one of the new pkgs with new depends will render the existing installs un-updateable.
It would really be great if we could discuss a way to add 'replaces' and 'conflicts' arrays in regards to that.

**Comment by fasheng** [comment]
@felixonmars @oberon2007 @mmetak

| new 2015 packages          | conflicts          | replaces                 | note                                                  |
|----------------------------|--------------------|--------------------------|-------------------------------------------------------|
| deepin-*                   |                    | dde-*                    | dde-api, dde-daemon, etc                              |
| deepin-desktop-schemas     | dde-daemon<=2.92.1 | deepin-default-gsettings |                                                       |
| deepin-session-ui          |                    | dde-workspace            |                                                       |
| deepin-sound-theme         | deepin-artwork     |                          |                                                       |
| deepin-nautilus-properties |                    |                          | dropped after new Deepin filemanager released |
| deepin-grub2-themes        |                    | grub-theme-deepin        |                                                       |
| deepin-mutter              |                    |                          |                                                       |
| deepin-wm                  |                    |                          |                                                       |
| libdui                     |                    |                          |                                                       |

| dropped 2014 packages    |
|--------------------------|
| dde-dock-applets         |
| dde-workspace            |
| deepin-compiz            |
| deepin-default-gsettings |
| deepin-qml-widgets       |
| libdeepin-webkit         |

**Comment by felixonmars** [comment]
deepin-qml-widgets is still needed by

   - deepin-movie
   - deepin-screenshot
   - deepin-social-sharing

Are they going to be updated to remove the dependency?

**Comment by fasheng** [comment]
No, just left `deepin-qml-widgets` there. I just forgot the package still be used by apps. ;)

**Comment by felixonmars** [comment]
Okay.

**Comment by oberon2007** [comment]
Thank you very much for the list, @fasheng , that makes things a lot clearer to me now :) So that means, one day we will basically switch **startdde**'s dependency from **deepin-compiz** to **deepin-wm** and the other new dependencies of dependencies and conflicts/replaces arrays should solve the rest. I will just have to coordinate things on the manjaro-end by making the necessary preparations and then adapt startdde-manjaro also when it is time ...
Do you have an estimated perspective for me when about this is going to happen?

**Comment by oberon2007** [comment]
I have this problem when trying to build **deepin-daemon**:
``gcc-go and go are in conflict``
but:
```
==> Packages which depend on gcc-go:
community/deepin-api 2.92.0-1
community/deepin-dbus-generator 0.6.2-1 (deepin-dev)
community/gost 1.8-1
community/rclone 1.25-1
```
and:
```
==> Packages which depend on go:
community/go-packages 20151027-1
community/liteide 27.2.1-1
```
How to solve this?

**Comment by fasheng** [comment]
@oberon2007 
A temporary solution, remove community/deepin-dbus-generator and use the one in OBS/arch-deepin:2015, or wait me to change the default compiler to gccgo in OBS which will be done this week.

And I also suggest continue the manjaro-deepin work after all packages moved to [community], because some packages may be changed by Felix, such as `go-packages`, I guess it will be split and the following PKGBUILDs will be changed ;)

**Comment by fasheng** [comment]
Here is my plan:
- `2015-11-20` upstream freeze code for Deepin 2015 alpha2
- `2015-11-22` rebuild all go packages in OBS through gccgo
- `2015-11-26` if things works fine, let @felixonmars move the rest packages to [community]
- `??` then @oberon2007 could continue the work for manjaro-deepin. at the same time, @mmetak and I will change obs/arch-deepin as a testing repo just like before(we will try to make it actor as an automated build system like Deepin did)

**Comment by oberon2007** [comment]
Cool, thank you! :)
Exchanging **deepin-dbus-generator** would be ok. but I still have the problem with **dde/deepin-api** dependeing on gcc-go ...!

**Comment by oberon2007** [comment]
Oh. I see. You mean to use the old **dde-api** meanwhile, right?

**Comment by fasheng** [comment]
@oberon2007 yes

**Comment by oberon2007** [comment]
I get this error when trying to build deepin-daemon now:
```
Makefile:46: recipe for target 'out/bin/dde-session-daemon' failed
make: *** [out/bin/dde-session-daemon] Error 1
```

**Comment by oberon2007** [comment]
Seems to be a wrong path:
```
env GOPATH="/usr/lib/go:/build/deepin-daemon-manjaro/src/dde-daemon/gopath" go build -ldflags '-s -w' -o out/bin/dde-session-daemon  pkg.deepin.io/dde/daemon/bin/dde-session-daemon
gopath/src/pkg.deepin.io/dde/daemon/appearance/subthemes/themes.go:4:2: cannot find package "dbus/com/deepin/api/cursorhelper" in any of:
	/usr/lib/go/src/dbus/com/deepin/api/cursorhelper (from $GOROOT)
	/build/deepin-daemon-manjaro/src/dde-daemon/gopath/src/dbus/com/deepin/api/cursorhelper (from $GOPATH)
gopath/src/pkg.deepin.io/dde/daemon/inputdevices/keyboard.go:5:2: cannot find package "dbus/com/deepin/api/greeterhelper" in any of:
	/usr/lib/go/src/dbus/com/deepin/api/greeterhelper (from $GOROOT)
	/build/deepin-daemon-manjaro/src/dde-daemon/gopath/src/dbus/com/deepin/api/greeterhelper (from $GOPATH)
gopath/src/pkg.deepin.io/dde/daemon/inputdevices/keyboard.go:10:2: cannot find package "pkg.deepin.io/dde/api/dxinput" in any of:
	/usr/lib/go/src/pkg.deepin.io/dde/api/dxinput (from $GOROOT)
	/build/deepin-daemon-manjaro/src/dde-daemon/gopath/src/pkg.deepin.io/dde/api/dxinput (from $GOPATH)
gopath/src/pkg.deepin.io/dde/daemon/inputdevices/mouse.go:5:2: cannot find package "pkg.deepin.io/dde/api/dxinput/utils" in any of:
	/usr/lib/go/src/pkg.deepin.io/dde/api/dxinput/utils (from $GOROOT)
	/build/deepin-daemon-manjaro/src/dde-daemon/gopath/src/pkg.deepin.io/dde/api/dxinput/utils (from $GOPATH)
gopath/src/pkg.deepin.io/dde/daemon/appearance/subthemes/themes.go:13:2: cannot find package "pkg.deepin.io/dde/api/themes" in any of:
	/usr/lib/go/src/pkg.deepin.io/dde/api/themes (from $GOROOT)
	/build/deepin-daemon-manjaro/src/dde-daemon/gopath/src/pkg.deepin.io/dde/api/themes (from $GOPATH)
```

**Comment by oberon2007** [comment]
I think I got it now ;)
Guess I need to build the newer dde-api-2.92.0 without gcc-go ...

**Comment by oberon2007** [comment]
unfortunately I cannot get dde-api-2.92.0 to build with go.
```
cannot find package "dbus/com/deepin/api/gtkthumbnailer" in any of:
	/usr/lib/go/src/dbus/com/deepin/api/gtkthumbnailer (from $GOROOT)
	/build/dde-api-manjaro/src/dde-api-2.92.0/gopath/src/dbus/com/deepin/api/gtkthumbnailer (from $GOPATH)
```

**Comment by fasheng** [comment]
@oberon2007 looks you should update go-packages first ;)

**Comment by oberon2007** [comment]
Oh. I had completely forgotten that I was using my own ... Thank you! :D

**Comment by fasheng** [comment]
@oberon2007 Looks like caused by the Makefile issue by dde-api, will fix it later...

**Comment by oberon2007** [comment]
I have built a new version of go-packages and used a later commit, that solves the issue with the sound-error :)

**Comment by oberon2007** [comment]
commit c37ebaf89c526f951e2bea84297a5cae0d665d75 seems to work

**Comment by oberon2007** [comment]
Ok. I'm nearly there to finally try deepin-2015 - exciting! :) But seems like I am still missing something...
After booting I get the new greeter, then the new sound-theme plus my background-image and I can hear that Skype is autostarted ;)
But: I appear to have no Dock and neither the Super-key nor right-click will do anything.
So I cannot access the launcher or control center for any further inquiries...
I have installed the following pkgs (built against go-packages) now:
**deepin-api
deepin-daemon
deepin-dbus-generator
deepin-desktop-schemas
deepin-mutter
deepin-nautilus-properties
deepin-session-ui
deepin-soundtheme
deepin-wm
libdui
startdde** (latest commit)
How about Compiz? Should it not be a dependency of startdde?

**Comment by fasheng** [comment]
@oberon2007 oh, I forget the front-end packages before, including deepin-dock, deepin-desktop, deepin-launcher, and the previous table already been updated ;)

**Comment by oberon2007** [comment]
:D ok. That explains a lot ;)

**Comment by oberon2007** [comment]
**deepin-control-center** also, I guess?

**Comment by fasheng** [comment]
@felixonmars 
New tags:

| project                |  new tag |
|------------------------|----------|
| dbus-generator         |    0.6.3 |
| go-lib                 |    0.4.2 |
| dbus-factory           |   2.92.1 |
| dde-api                |   2.92.1 |
| dde-daemon             |   2.93.1 |
| startdde               |   2.92.1 |
| libdui                 |    1.2.1 |
| dde-control-center     |   2.91.1 |
| dde-dock               |   2.90.1 |
| dde-desktop            |   2.90.1 |
| dde-launcher           |   2.90.1 |
| dde-session-ui         |   2.90.1 |
| deepin-notifications   |    2.3.3 |
| deepin-file-manager    |    0.1.1 |
| deepin-mutter          | 3.18.1.2 |
| deepin-wm              |   0.91.3 |
| deepin-desktop-schemas |   2.91.1 |
| deepin-screenshot      |    3.1.3 |
| deepin-qml-widgets     |    2.3.1 |
| deepin-social-sharing  |    1.1.1 |

**NOTE:** Once `dbus-generator` updated, we need rebuild go-packages(go-dlib)/dbus-factory firstly, then rebuild dde-api/dde-daemon/startdde.

**Comment by felixonmars** [comment]
Current status:

Moved and updated: dbus-generator/dbus-factory/dde-api/libdui/dde-dock/deepin-notifications/deepin-mutter/deepin-wm/deepin-desktop-schemas/deepin-screenshot/deepin-qml-widgets/deepin-social-sharing

On hold: dde-daemon (Failed to build)

PR sent: startdde (Only one LDFLAGS fix, no other problems)

Not started yet: dde-control-center/dde-desktop/dde-launcher/dde-session-ui/deepin-file-manager

**Comment by fasheng** [comment]
@felixonmars 

Thanks.

The gccgo build issue  for dde-daemon(exactly, is go-dlib/pulse) for Archlinux/gccgo is caused by cgo which already fixed in go `1.5`. But what different from Debian is that, Archlinux make gccgo conflicts with go, so the cgo version we are using still is the broken `1.4`.

And the developer is working hard for it now...

**Comment by felixonmars** [comment]
Thanks a lot for that :)

**Comment by fasheng** [comment]
dde-daemon gccgo build issue solved now, please try the latest commit again:
`238151791673412dedf333363b3a37343c461acb`

**Comment by fasheng** [comment]
Just forgot point out the project ;)
`go-lib` -> `238151791673412dedf333363b3a37343c461acb`

**Comment by felixonmars** [comment]
All mentioned packages were moved and updated. I'll adjust the replaces/conflicts array tomorrow.

**Comment by fasheng** [comment]
Great job, thanks!

**Comment by oberon2007** [comment]
Awesome! Curiousely waiting :) My own experiments with the packages went quite well despite I was not able, yet to launch the control center from the dock or the launcher properly - could only do it from the terminal so far - but the problem might be my custom manjaro desktop-schemas - will try again with the default when the arch pkgs are ready.
One strange issue: When I try to logout I get the dialog screen of choices (logout, restart and so on) in Chinese!! 8-}

**Comment by philmmanjaro** [comment]
@oberon2007: seems you have to learn **Chinese** after all ;) I already merged the packages to our **unstable** branch.

**Comment by oberon2007** [comment]
谢谢大家！

**Comment by fasheng** [comment]
@oberon2007 
Wow，amzing! Excited to discuss you in Chinese :smile:

**Comment by felixonmars** [comment]
@oberon2007 I cannot reproduce the problem. I use `en_US.UTF-8` locale and the dialog is filled with English words correctly.

**Comment by oberon2007** [comment]
Yes, @felixonmars , when I use your original pkgs it's not a problem. As I suspected already this must be related to the custom pkgs. I'm starting off again now from a regular build and then see how to best accomplish my customizations :)

**Comment by oberon2007** [comment]
What's the new configuration for file-manager pkgs? What to install now? **deepin-file-manager**, **nautilus**? **deepin-nautilus-properties**? (not available in arch or deepin:2015 atm)

**Comment by oberon2007** [comment]
I think whatever the nautius pkgs neede are, they should be depends of **deepin-desktop** or **deepin-dock** since they will not work properly without.

**Comment by fasheng** [comment]
there is no deepin filemanager gui now, just a backend and used by deepin-desktop

**Comment by oberon2007** [comment]
So which pkgs to install? **nautilus** obvioiusly, then we have a **deepin-file-manager** pkg available. What about **deepin-nautilus-properties** now? Do I still need that?

**Comment by oberon2007** [comment]
Right now dde-desktop doesn't seem to work for me (at least not in vbox)
```
$ dde-desktop
pci id for fd 12: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
```
Also: In **control-center** under "Personalization" I see no entries under **Theme** or **Fonts**.
Seems like maybe there is a problem with **deepin-artwork-themes**?
The dir **/usr/share/backgrounds/** doesn't exist while gsettings **com.deepin.dde.appearance** has ``background file:///usr/share/backgrounds/default_background.jpg``

**Comment by felixonmars** [comment]
@oberon2007 All but the first issue have already been addressed in the Arch [community] packages. Please try `virtualbox-guest-modules` for the first issue :)

**Comment by oberon2007** [comment]
@felixonmars what do you mean by "addressed" ? I am using all your latest packages with nothing customized right now. ``linux41-virtualbox-guest-modules 5.0.8-1`` are installed of course...

**Comment by oberon2007** [comment]
I am still not clear about which pkgs need to be installed. Is **deepin-nautilus properties** still needed? Should **deepin-file-manager** already be installed? In any case I am surprised that **nautilus** is not a dependency of any deepin pkg while as far as I understand, neither deepin-desktop nor deepin-dock work without it.

**Comment by felixonmars** [comment]
`addressed` means `dealt with` in the context :P 

I have updated deepin-dock to depend on nautilus, and I'm not sure of `deepin-nautilus-properties` either.

**Comment by oberon2007** [comment]
@felixonmars I'm sorry! I didn't realize that your latest pkgs have not been copied over to the manjaro-repos, yet - I will try again later, then :)
vb guest-modules were already installed of course and I had the same situation running on hardware from a USB ... I'll report back as soon as I have the latest pkgs installed.

**Comment by felixonmars** [comment]
virtualbox guest module packages may have problems with latest xorg, but my memory may not be good :3

**Comment by oberon2007** [comment]
Another little detail: Maybe **deepin-desktop-schemas** should depend on **deepin-gtk-theme** (maybe also **deepin-sound-theme** or **deepin-artwork-themes**?

**Comment by felixonmars** [comment]
You are right. I am adding all these 3 deps.

**Comment by oberon2007** [comment]
So. I just built a new ISO with all the latest community pkgs in group deepin and deepin-extra.
The default background is now showing but cannot be changed and **deskop icons** are not displayed. When I add a program from the launcher with right-click>"Send to desktop" the status is changed only in that next time I right-click that same app in the launcher the selection shows "Remove from desktop" ;)
**Theme** and **Fonts** in **Personalization** are still emtpy.
Setting the fonts has no effect and is shown empty again after relogging.
**Icons** cannot be changed, Deepin-2014 theme is not present.
Selection of **User icons** is visible but they are not applied. Neither in the control center nor in the greeter... and it seems that there is no option to **add a new user**, or am I not finding it?

**Comment by oberon2007** [comment]
The issue with the **user icons** is solved by installing **accountsservice**. ... ;)

**Comment by oberon2007** [comment]
In **efficient** or **classic** mode desktop icons for Computer and Trash are displayed, but not any added apps.

**Comment by oberon2007** [comment]
With accountsservice installed the user icon is now displayed in the greeter and in the user list, but after reboot the header of "Home" in Control Center is empty again.

**Comment by felixonmars** [comment]
I failed to find out how the greeter was calling accountsservice's dbus interface, any hints?

I have added accountsservice as dependency of deepin-dbus-factory, which is a dependency of deepin-control-center.

**Comment by fasheng** [comment]
@oberon2007 
For the **Personalization** issues, please update deepin-artwork-themes to the latest **15.10.1.20151118-2**

@felixonmars 
In fact, you should add accountsservice to depends of deepin-daemon, all the code in dbus-factory is just a wrapper. And in upstream, deepin-daemon depends on dbus-factory for the golang dbus wrapper code, but we split them in arch :P

**Comment by felixonmars** [comment]
I see, got it. I'm updating `deepin-daemon` to include my 2 patches (hehe <(=^_^=)>) and the dependency on accountsservice, and also fixing the missing `deepi n-daemon` dependency on `deepin-session-ui`.

**Comment by felixonmars** [comment]
Update: More dependency fixes were applied to deepin-session-ui, deepin-desktop, deepin-dock, deepin-launcher, and deepin-control-center. These were extracted from dbus interface calls in code.

**Comment by oberon2007** [comment]
@fasheng **deepin-artwork-themes 15.10.1.20151118-2** is what I have already installed. Personalization not working though. Will see tonight if @felixonmars 's latest updates arrive if that helps... :)

**Comment by fasheng** [comment]
so there is no theme in list, right? and please show us your theme.ini that in /usr/share/personalization and ~/.local



2015年11月26日 下午7:31, 下午7:31，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Exactly, Theme-list is empty.
**/usr/share/personalization/themes/Deepin/theme.ini** is the default installed by **deepin-artwork-theme
```
[Theme]
Id=Deepin
Name=Deepin
Name[en_GB]=Deepin
Name[en_US]=Deepin
Name[zh_CN]=Deepin
Name[zh_HK]=Deepin
Name[zh_TW]=Deepin

[Component]
GtkTheme=Deepin
IconTheme=Deepin
CursorTheme=Deepin-Cursor
FontName=sans-serif
FontMono=monospace
FontSize=11
BackgroundFile=file:///usr/share/backgrounds/deepin_default_background.jpg
SoundTheme=deepin
```
**personalization/** in **~/.local/share/** has not been created at all!!

**Comment by fasheng** [comment]
The theme.ini only works with all components matched, if your deepin-daemon and deepin-control-center are the latest pkgs, too, try to change the font to some other one, and re-enter personalization module to see the result



2015年11月26日 下午8:16, 下午8:16，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
Well, @fasheng that's exactly what I am doing. The pkgs are all the latest as of today. When I set the fonts, close and reopen Control Center, the Font fields are empty again and Theme Deepin never appears.

**Comment by jouyouyun** [comment]
@oberon2007 , Please paste the following commands's outputs
```shell
$ ls /usr/share/themes
$ ls /usr/share/icons
$ ls /usr/share/backgrounds
$ fc-match sans-serif
$ fc-match monospace
```
Thanks!

**Comment by fasheng** [comment]
@felixonmars 
How about replaces, conflicts or provides `dde-dock-applets` in `deepin-control-center`, so updating packages from OBS to [community] will be more easily ;)

**Comment by felixonmars** [comment]
Sure, updating :)

Also if no objection, I am going to move the current [community-testing] package set to [community], since it's proven to be more stable :)

**Comment by fasheng** [comment]
Great, thanks for the external work for [community-testing].

And @oberon2007, you could try to update packages from your `manjaro-deepin-15.10dev-x86_64.iso`, if works, I will close this issue and complete milestone `2015.a2`.

**Comment by oberon2007** [comment]
Thank you all! We have the [community-testing] pkgs already in the manjaro-repos and I am busy making them work on a new ISO build. The plan is to publish a manjaro-deepin-15.12 in a few weeks. The dev-builds were more experimental and will not need to be updated.
Some people have installed the (15.12-preview)[https://sourceforge.net/projects/manjaro-deepin/] which still uses 2014.3 pkgs but I am sure we'll be able to update them as soon as I have the customization sorted.
So I agree: Transition is done. :)

**Comment by fasheng** [comment]
Thanks all, we finish the great task. :+1:
